config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    post 'square/:name/:click' => 'games#click'
    get 'profile' => 'games#profile', as: 'profile'
    root to: 'games#index'
end

app/views/layouts/_login_modal.html.slim
.modal.fade.in#login
    .modal-dialog
        .modal-content
            .modal-header
                button.close aria-hidden='true' data-dismiss='modal' type='button' ×
                h2.modal-title Авторизация
            = simple_form_for(User.new, as: :user, url: session_path(:user)) do |f|
                .modal-body
                    .col-md-7= f.input :username, required: true, autofocus: true, label: 'Имя пользователя'
                    .col-md-7= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable), label: 'Пароль'
                    .clearfix
                    p= f.button :submit, 'Авторизация', class: 'btn btn-small btn-success'

app/views/layouts/_nav.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role='navigation'
    .navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
    .navbar-collapse.collapse
        ul.nav.navbar-nav
            li= link_to 'Новая игра', root_path
            - if current_user
                li= link_to 'Профиль', profile_path
    .auth_box
        - if user_signed_in?
            span.hidden-xs
                span= "Вы вошли как #{current_user.username}"
            = link_to 'Выход', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-danger', id: 'destroy'
        - else
            = link_to 'Регистрация', '#sign_up', 'data-toggle' => 'modal', id: 'up', class: 'btn btn-sm btn-success'
            = link_to 'Вход', '#login', 'data-toggle' => 'modal', id: 'log', class: 'btn btn-sm btn-success'

app/views/layouts/_sign_up_modal.html.slim
.modal.fade.in#sign_up
    .modal-dialog
        .modal-content
            .modal-header
                button.close aria-hidden='true' data-dismiss='modal' type='button' ×
                h2.modal-title Регистрация
            = simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f|
                .modal-body
                    .col-md-7= f.input :username, required: true, autofocus: true, label: 'Имя пользователя'
                    .col-md-7= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable), label: 'Пароль'
                    .col-md-7= f.input :password_confirmation, required: true, label: 'Подтверждение пароля'
                    .clearfix
                    p Минимальная длина пароля - 8 символов
                    p= f.button :submit, 'Регистрация', class: 'btn btn-small btn-success'

app/views/layouts/application.html.slim
doctype html
html
    head
        title Mines
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    body
        / фоновое изображение
        .inside
            .shadow
        / навигация
        = render 'layouts/nav'
        = render 'layouts/login_modal'
        = render 'layouts/sign_up_modal'
        .container
            .row
                = yield